# Generated by Django 4.0.2 on 2022-04-17 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medics', '0002_alter_medicrecord_blood_group_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicrecord',
            name='address',
        ),
        migrations.RemoveField(
            model_name='medicrecord',
            name='age',
        ),
        migrations.RemoveField(
            model_name='medicrecord',
            name='blood_group',
        ),
        migrations.RemoveField(
            model_name='medicrecord',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='medicrecord',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='medicrecord',
            name='middle_name',
        ),
        migrations.AddField(
            model_name='medicrecord',
            name='date_of_birth',
            field=models.DateField(auto_now_add=True, max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='medicrecord',
            name='email',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='medicrecord',
            name='full_name',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='medicrecord',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='medicrecord',
            name='home_address',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='medicrecord',
            name='occupation',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='medicrecord',
            name='phone_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medicrecord',
            name='state',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='medicrecord',
            name='zip_code',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
